### ISSUE TITLE
Update README.md with more advice / knowledge about what to actually do instead of just standard stuff

### ISSUE THREAD

**Issue by ajgrinds** [garythebot/Gary-the-Bot#10]

**Comment by caelinsutch** [comment]
How is it deployed? Can you give some more info? I added in some stuff, in read-me-updates branch

**Comment by caelinsutch** [comment]
Rip @ajgrinds permission denied, can you add me as a contributer?

**Comment by ajgrinds** [comment]
Fixed

**Comment by Vapour38** [comment]
@ajgrinds You are talking about the testing on your machine part right? Cause all you need to do is invite it now
