### ISSUE TITLE
Add to https://discordbots.org/bot/new

### ISSUE THREAD

**Issue by ajgrinds** [garythebot/Gary-the-Bot#8]

**Comment by Vapour38** [comment]
I would do this but I don't have the token so you will have to

**Comment by ajgrinds** [comment]
It's not the token, it's the client ID. I don't pass the token anywhere. But we need a description

**Comment by Vapour38** [comment]
Is this done now?

**Comment by ajgrinds** [comment]
Yeah if I close it, it means it's done

**Comment by Vapour38** [comment]
Alright, I was just checking

**Comment by ajgrinds** [comment]
It got declined cuz we don't have a help command

**Comment by Vapour38** [comment]
@ajgrinds 
Currently, Gary-the-Bot is a work in progress, but the devs are always looking at new features to add. A list of commands are on their way, but in the mean time, you can go to the GitHub page to see all the features, or the Discord Support Server, where you can ask the devs questions or get help with the setup.
**Offical GitHub page:**
https://github.com/garythebot/Gary-the-Bot
**Offical Discord Server:**
https://discord.gg/E5vTZ4H
